### PR TITLE
Make dokka Gradle task cacheable

### PR DESCRIPTION
**Pull request by devisnik**
adds support for local and remote caching to `DokkaTask`.

addresses https://github.com/Kotlin/dokka/issues/453

### CODE REVIEW

**Comment by sellmair** [comment]
Hey @devisnik, thanks for your contribution 👍 
Would you be able to rebase this on our latest dev-0.11.0 branch?

**Comment by devisnik** [comment]
Sorry for the late reply.
I'll look into redoing the changes onto `dev-0.11.0`. Seems the test infrastructure has changed quite a bit on that branch.

**Comment by sellmair** [comment]
Please also check the Gradle maintenance branch! It might make sense to wait for that and adjust accordingly if there are still issues!

**Comment by devisnik** [comment]
@sellmair Do you mean `gradle-plugin-maintenance` ? 
I have a working version based on `dev-0.11.0` now. Do you want me to PR that? Or should the change be based on `gradle-plugin-maintenance` ?

**Comment by sellmair** [comment]
Yes, I mean that branch. 
But I think this should be the plan: We might want to merge #1194 first and then adapt your changes on top of it ☺️

**Comment by devisnik** [comment]
@sellmair Sounds good to me. 😄 
I've created #1296 for the changes on `dev-0.11.0`. We might want to adapt that one after #1194 has been merged.

Should we close this one?

**Comment by sellmair** [comment]
Thanks for the effort. We are actually now branching from/targeting master instead of `dev-0.11.0`, but those branches are not drastically different at the moment. 

But there is no need of closing this right now. I will take care of it once the Gradle Plugin changes are merged ☺️

**Comment by keturn** [comment]
Superseded by #1905?

**Comment by eskatos** [comment]
Can't this be closed?

**Comment by IgnatBeresnev** [comment]
It does indeed look like it was re-implemented in https://github.com/Kotlin/dokka/pull/1905, so I'll be closing the PR. Thank you for your effort though!

> Can't this be closed?

I'm reluctant to close old PRs on the basis that they are old, it's rude and we might miss out on useful changes, but it takes time to verify and revive them, and we haven't had time lately. It's on our list though.

If you see similarly stale PRs/issues that have been implemented, please point it out, I'd be happy to have a closer look

**Pull request closed without merging**
