### PR TITLE
Enable Gradle Enterprise

### PR DESCRIPTION
**Pull request by Goooler**
https://docs.gradle.com/enterprise/gradle-plugin/

### CODE REVIEW

**Comment by Goooler** [comment]
We can use this to speed up builds, if necessary we can publish the build scan on CI only like this:
https://github.com/apache/groovy/blob/3405c7be6d64f462a76b6a864aecdbdcbbe80e89/gradle/build-scans.gradle#L20-L55

**Comment by IgnatBeresnev** [comment]
> if necessary we can publish the build scan on CI only like this

Oooh, yes, that would make me happy :) Certainly would not hurt

**Comment by Goooler** [comment]
https://github.com/Kotlin/dokka/actions/runs/2920255208

image

**Review by vmishenev — APPROVED** [review]
As for me, it is extremely useful. Thank you for contributing.

**Review by IgnatBeresnev — APPROVED** [review]
Thanks!

**Pull request merged**
