### PR TITLE
Add options to include links to stdlib.

### PR DESCRIPTION
**Pull request by stephenbyrne-mfj**
https://github.com/Kotlin/dokka/issues/188
Do not connect to the internet for stdlib links by default.
Removed "noStdlibLink" option (which only controlled kotlin stdlib, not
java, and was enabled by default).
Added "kotlinStdlibLink" and "javaStdlibLink" options, which are
disabled by default.

### CODE REVIEW

**Comment by semoro** [comment]
Sorry, but we can't accept this PR because of:
 * Option to disable JDK links already added, but not yet merged into dev (8e9e768d51d83c2ae1641a0c2d9ec4614c109117)
 * It changes the reasonable default
 * Disabling default external links will result in a drop in overall documentation quality, as no-one will override the default
 * It doesn't provide a deprecation cycle. This would result in unexpected behavior change for users and will be treated as a regression

**Comment by stephenbyrne-mfj** [comment]
I would argue that requiring a connection to oracle.com at run time is **not** a reasonable default, but rest of the points stand.

**Comment by semoro** [comment]
Providing option to disable such behavior seems fine to resolve this issue. Don't you think so?

**Comment by stephenbyrne-mfj** [comment]
Yes, when 8e9e768 is released, I will be content.

**Pull request closed without merging**
