### PR TITLE
Add Gradle Kotlin DSL documentation

### PR DESCRIPTION
**Pull request by johanvergeer**
Simple addition for users of Gradle Kotlin DSL

### CODE REVIEW

**Comment by StefMa** [comment]
There is no need to make it that complicated.
```kotlin
tasks.withType<DokkaTask> {
}
```
is enough..

**Comment by ihostage** [comment]
Why not?
```
tasks.dokka {
    outputFormat = "javadoc"
    outputDirectory = "$buildDir/javadoc"
    jdkVersion = 8
    reportUndocumented = true
    impliedPlatforms = mutableListOf("JVM")
}
```

**Comment by reitzig** [comment]
As of 0.9.18, @ihostage's proposal works. Or also:

```kotlin
tasks {
	dokka {
		...
	}
}
```

**Comment by sellmair** [comment]
Something similar was implemented by #922.

**Comment by StefMa** [comment]
Haha nice workaround 😂

**Comment by sellmair** [comment]
Hehehe, its not a workaround if there are not obstacles to in the way to _work around_ 😛

**Pull request closed without merging**
