### PR TITLE
Include information about local publish in README.md

### PR DESCRIPTION
**Pull request by MarcinAman**

### CODE REVIEW

**Comment by sellmair** [comment]
Why are people not using our nightly dev builds? 🙄

**Comment by MarcinAman** [comment]
> Why are people not using our nightly dev builds? 🙄

Maybe they use but imho it is worth to at least inform that there is an option to easily build new versions of dokka. This is also important if somebody would like to contribute and see how the changes affect the documentation

**Comment by sellmair** [comment]
I see: This might be good informations for developers with little Gradle experience. You're right!
The issue is, that the Readme is already pretty long and I am not sure if including this information is really worth it. 
Would be interested in your opinion @kamildoleglo !

**Comment by kamildoleglo** [comment]
I'd put it in the CONTRIBUTING.md

**Comment by MarcinAman** [comment]
Ok, done

**Pull request merged**
