### PR TITLE
support for gradle multiproject

### PR DESCRIPTION
**Pull request by Kordyjan**
There are lots of problems (eg. #284 #269 #278 #319) resulting from the fact that dokka gradle task is only aware of the project that it was defined in and not its dependencies.

In this pull request I'm making dokka aware of dependencies between projects. Now generating documentation depends on generating documentation for dependencies. In the same manner documentations of dependencies are treated as inputs to project documentation generation. This allows us to have a realiable relative links between documentations of different subprojects.

Sadly this solution is not working for javadoc output format, because resolver for javadoc [is not finished](https://github.com/Kotlin/dokka/blob/dev-pre/core/src/main/kotlin/Kotlin/ExternalDocumentationLinkResolver.kt#L230), but as soon as more cases are added to this resolver the links to javadoc will start to work properly.

### CODE REVIEW

**Comment by pyricau** [comment]
Any chance this will make it into a future release?

**Comment by RaymondChan1** [comment]
I would definitely love to see this implemented. Good luck!

**Comment by RingerJK** [comment]
are you folks gonna merge it?

**Comment by kamildoleglo** [comment]
This has been fixed in the new Dokka

**Pull request closed without merging**
