### PR TITLE
Remove 'by' property setter helper function

### PR DESCRIPTION
**Pull request by aSemy**
Part of #2700 

I found these extension functions very confusing. I'm not sure what their purpose is. Do they only rename an existing function? 

It's confusing because 'by' is already a Kotlin keyword for delegation, but these extension functions don't do anything with delegation. I think using the normal `.set()` function makes the code more readable and understandable because `.set()` is a common Gradle function.

This PR includes changes from 

* #2702 
* #2701  
* #2705

### CODE REVIEW

**Comment by IgnatBeresnev** [comment]
Not sure why these methods were introduced (the PR itself is huge, #1194), but I agree that it can be confused with Kotlin's `by` keyword, and overall would make the code a little easier to understand.

I'm ready to approve it once it has been rebased and contains no changes from other PRs, so let's wait for the other ones to be merged/closed first

**Comment by Goooler** [comment]
Use `by` to set values in Kotlin dsl is reasonable, no need to replace it.

**Comment by IgnatBeresnev** [comment]
> Use by to set values in Kotlin dsl is reasonable, no need to replace it.

That's not part of the DSL though, and I honestly fail to see what value it brings. If it's considered to be a good practice, could you link to examples/docs/etc?

`by` makes me think it's a delegate of some sort, or that there's some complicated logic with how the value is assigned or computed, whereas it's a simple `set`

**Comment by Goooler** [comment]
Alright, I haven't found strong evidence for using `by` in setting properties, it might due to my false memory.

**Comment by aSemy** [comment]
> Alright, I haven't found strong evidence for using `by` in setting properties, it might due to my false memory.

Are you thinking about how you can do `val someTask by tasks.registering { }`? https://docs.gradle.org/current/userguide/kotlin_dsl.html#using_kotlin_delegated_properties

**Comment by IgnatBeresnev** [comment]
I'd be happy to merge it now the changes don't include the postponed #2702 and #2705

**Comment by aSemy** [comment]
done https://github.com/Kotlin/dokka/pull/2834/files

**Pull request closed without merging**
