### PR TITLE
Exclude top-level const val from generated getters

### LINKED ISSUE #1624: dokkaJavadoc incorrectly renders top-level const val
**Describe the bug**
Javadoc output displays these as private final fields on the generated `{Filename}Kt` class, with final getters.

**Expected behaviour**
Javadoc output displays these as public static final fields on the generated `{Filename}Kt` class, without getters, reflecting the generated bytecode.

**To Reproduce**
Create Kt file with the following content:
```kotlin
const val FIRST = "String"
const val SECOND = 2
```

**Dokka configuration**
Configuration of dokka used to reproduce the bug

```groovy
dependencies {
    classpath "org.jetbrains.dokka:dokka-gradle-plugin:1.4.10.2"
}
...
apply plugin: 'org.jetbrains.dokka'
```

**Installation**
- Operating system: Windows
- Build tool: Gradle 6.3
- Dokka version: 1.4.10.2

### PR DESCRIPTION
**Pull request by bishiboosh**
This fixes #1624

### CODE REVIEW

**Comment by bishiboosh** [comment]
I've just realized I've not tested this with Javadoc tests, and so I can't assume this is working right now, I'll look into it

**Comment by MarcinAman** [comment]
Hi, is this PR ready for review?

**Comment by bishiboosh** [comment]
@MarcinAman yup !

**Comment by bishiboosh** [comment]
@MarcinAman done, let me know if there are any issues

**Review by kamildoleglo — APPROVED** [review]

**Comment by MarcinAman** [comment]
Thanks ☺️

**Pull request merged**
