### PR TITLE
Skip empty packages by default

### PR DESCRIPTION
**Pull request by kamildoleglo**

### CODE REVIEW

**Comment by sellmair** [comment]
Do you want this in 1.4.0 or in 1.4.0-rc? 
Please select the milestone ☺️

**Comment by sellmair** [comment]
@kamildoleglo ? 🙄

**Comment by kamildoleglo** [comment]
Sorry, didn't get the notification 😢 
It's up to you, this is not a crucial thing, we can wait for 1.4.0

**Comment by sellmair** [comment]
Please add the milestone 😢  (I did it now myself)

**Pull request merged**
