### PR TITLE
Fix IDEA Inspections

### PR DESCRIPTION
**Pull request by Xerus2000**

### CODE REVIEW

**Comment by Xerus2000** [comment]
Hey, any problems with this PR?

**Comment by semoro** [comment]
Basically right now is big refactoring are in branches, so it will cause a lot of conflicts, but I can request changes on this PR once it can be done safely

**Comment by Xerus2000** [comment]
Anything moving here?

**Comment by KrystianUjma** [comment]
@Xerus2000 I will merge soon

**Comment by KrystianUjma** [comment]
@Xerus2000 thank you for your contribution 🎉

**Pull request merged**
