### PR TITLE
Javadoc package-list

### PR DESCRIPTION
**Pull request by MarcinAman**

### CODE REVIEW

**Comment by Kordyjan** [comment]
I understand opening classes for page nodes, but please keep in mind two things:
- methods that are an implementation of some abstract method and are not supposed to be overridable down the line should be marked as `final override`.
- Do not declare properties in inheriting class constructor if they are already declared in base class. It should look like in the following example:
```kotlin
interface A {
    val a: Int
}

class B(
    final override val a: Int 
): A 

class C(a: Int): B(a) // here `a` is ordinary parameter, not property
```
This should result in less bloated bytecode and easier debugging.

**Comment by MarcinAman** [comment]
@Kordyjan something like in latest commit?: https://github.com/Kotlin/dokka/pull/1237/commits/a849b476fd2c1160c9638fb2ee9a82515a6dae0a

**Review by Kordyjan — APPROVED** [review]

**Comment by sellmair** [comment]
This is not for the 1.4.0 release? 🙄

**Comment by sellmair** [comment]
Cherry picked into 1.4.0 🍒

**Pull request merged**
