### PR TITLE
Remove leftover from javadoc

### PR DESCRIPTION
**Pull request by MarcinAman**
i don't know if it should go to RC or 1.4.0. Its up to you

### CODE REVIEW

**Comment by sellmair** [comment]
I think this would require to be rebased 🙄

**Comment by MarcinAman** [comment]
<3 Github rebase action works after the merge to master

**Comment by sellmair** [comment]
But now only the TC checks were running 😢

**Comment by sellmair** [comment]
Also please add a milestone to this PR so I know if you expect me to pick this 🙄

**Pull request merged**
