### PR TITLE
Fix java translation

### LINKED ISSUE #1284: DokkaJavadoc does not respect JVMName
**Describe the bug**
When using `dokkaJavadoc`, the class names or method names are the Kotlin ones, instead of being the ones specified by `@JvmName`

**Expected behaviour**
Use names specified in `@JvmName` when rendering to Javadoc.

**To Reproduce**
Using this sample project https://github.com/bishiboosh/dokka-issue-sample call the `dokkaJavadoc` task and see the generated documentation

**Dokka configuration**
No specific configuration

**Installation**
- Operating system: Linux
- Build tool: Gradle v6.1.1
- Dokka version: 1.4.0-rc

### PR DESCRIPTION
**Pull request by bishiboosh**
This (tries to) fix #1284

### CODE REVIEW

**Comment by bishiboosh** [comment]
@MarcinAman ok so as I said in #1284, this is what I've done so far. I hope most of it will be usable but I may have gone in a wrong direction.

First, I've added file annotations parsing and transformation in `DefaultDescriptorToDocumentableTranslator` (with accompanying tests).

The main part of the work is done in `KotlinToJavaConverter`, as I wanted to change the representation of the elements here and not just change their names in the `SignatureProvider` (that's what I did first, following your advice, but this caused a bunch of linking errors in the final documentation).
I'll let you peruse (and probably fix) my changes, but what I've done so far is:
- use JVM name from file annotation to change class name of top-level elements
- handled `JVMName` on functions, classes-like and properties (I think callables still need to be modified, I've left a TODO about that)
- handled `JVMSynthetic` to ignore elements
- handled `JVMField` and its interaction with `const` to transform functions to static

Let me know if any of my code isn't understandable, I'll try to help as best as I can, sorry I wasn't able to finish.

**Comment by MarcinAman** [comment]
Thanks, you rock 🥇 

For sake of being reviewable i've split this into 2 PR-s. First one is: https://github.com/Kotlin/dokka/pull/1675
I'll continue the work on the other 2 ☺️

**Comment by bishiboosh** [comment]
@MarcinAman seeing as you just merged #1675 (🥳), do you want me to close this PR or do you still need it ?

**Comment by MarcinAman** [comment]
I think it is no longer needed. Thank you very much for this 🥇

**Comment by bishiboosh** [comment]
@MarcinAman I saw that you've done `JvmName` and `JvmField`, do you want me to backport what I did on `JvmOverloads` (and/or `JvmSynthetic`) or are you working on it ?

**Comment by MarcinAman** [comment]
I the following 2 weeks i wont be able to do it. If you have some spare time, sure go ahead. Even if you wont finish it I can pick up the work

**Comment by bishiboosh** [comment]
I'll try to do it today or tomorrow if I can, and I'll let you know (I'll
open a new PR for this)

Le mer. 27 janv. 2021 à 08:41, Marcin Aman <notifications@github.com> a
écrit :

**Pull request closed without merging**
