### PR TITLE
Dokka Gradle Plugin: Implement Gradle Worker Daemon for Dokka generation

### PR DESCRIPTION
**Pull request by aSemy**
Refactor the way dokka-gradle executes a Dokka generation task to use a [Gradle Worker Daemon](https://docs.gradle.org/current/userguide/worker_api.html#creating_a_worker_daemon). The Worker is configured to use the same classpath as the existing reflection-based process.

Using a Worker Daemon completely replaces the existing 'reflection magic'. I think this is a lot more simple and easier to understand than the previous method of using reflection to create an instance.

This PR is a further improvement upon #2709, which required a main method. Using the Gradle Worker API means the dokka-core code can be called idiomatically. However, I am not sure about the compatibility with Gradle versions. #2709 might be more compatible...

Benefits:

* idiomatic Kotlin
* idiomatic Gradle
* no reflection magic
* easier to configure/debug/test
* no API changes for users - this should 'just work'

I haven't tested extensively so there might be some breaking changes. Of particular note:

* is the logging output still present and as expected
* is the Worker API compatible with the versions of Gradle that Dokka must support?

This PR includes 

* #2702 
* #2759

### CODE REVIEW

**Comment by qwwdfsad** [comment]
I've tried to run it against Ktor and stumbled across the following exception:

```
Caused by: java.lang.NoClassDefFoundError: com/intellij/openapi/diagnostic/Logger$Factory
        at org.jetbrains.dokka.base.DokkaBase.<clinit>(DokkaBase.kt:287)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
```

**Comment by qwwdfsad** [comment]
Thanks! 
The contribution indeed looks very promising (reflection magic is something we strive to get away from), but unfortunately I can build neither coroutines nor Ktor with this change:
```
> A failure occurred while executing org.jetbrains.dokka.gradle.workers.DokkaGeneratorWorker
   > org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(Lcom/intellij/openapi/Disposable;Lorg/jetbrains/kotlin/config/CompilerConfiguration;Lorg/jetbrains/kotlin/cli/jvm/compiler/EnvironmentConfigFiles;)Lorg/jetbrains/kotlin/cli/jvm/compiler/KotlinCoreEnvironment;
```

I've also verified that without your patch, coroutines can be built with Dokka from `master` branch. Could you please take a look?

**Comment by qwwdfsad** [comment]
It seems like Gradle Worker is missing some dependencies

**Comment by aSemy** [comment]
Thanks for trying it! Yes it's possible that dependencies might be missing now that the Dokka worker executes in a separate process. It should be easy to add them back in though. 

(Missing dependencies isn't a big problem, even if it's annoying. Since Dokka creates a Gradle Configuration anyone would be able to fix this themselves, should a similar problem arise.)

It's been a while since I've looked at this.. I can try figuring out what's missing. Do you have the full stack trace? Are there any clues in there?

**Comment by qwwdfsad** [comment]
I've checked it manually 

Stacktrace:
```
Caused by: java.lang.NoSuchMethodError: org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(Lcom/intellij/openapi/Disposable;Lorg/jetbrains/kotlin/config/CompilerConfiguration;Lorg/jetbrains/kotlin/cli/jvm/compiler/EnvironmentConfigFiles;)Lorg/jetbrains/kotlin/cli/jvm/compiler/KotlinCoreEnvironment;
        at org.jetbrains.dokka.analysis.AnalysisEnvironment.createCoreEnvironment(AnalysisEnvironment.kt:107)
        at org.jetbrains.dokka.analysis.EnvironmentAndFacadeKt.createEnvironmentAndFacade(EnvironmentAndFacade.kt:30)
        at org.jetbrains.dokka.analysis.KotlinAnalysisKt.KotlinAnalysis(KotlinAnalysis.kt:13)
        at org.jetbrains.dokka.analysis.KotlinAnalysisKt.KotlinAnalysis$default(KotlinAnalysis.kt:11)
        at org.jetbrains.dokka.base.DokkaBase$defaultKotlinAnalysis$2$1.invoke(DokkaBase.kt:191)
        at org.jetbrains.dokka.base.DokkaBase$defaultKotlinAnalysis$2$1.invoke(DokkaBase.kt:43)
        at org.jetbrains.dokka.plugability.LazyEvaluated.get$core(LazyEvaluated.kt:8)
        at org.jetbrains.dokka.plugability.DokkaContextConfigurationImpl.single(DokkaContext.kt:159)
        at org.jetbrains.dokka.base.translators.psi.DefaultPsiToDocumentableTranslator.<init>(DefaultPsiToDocumentableTranslator.kt:818)
        at org.jetbrains.dokka.base.DokkaBase$psiToDocumentableTranslator$2$1.invoke(DokkaBase.kt:69)
        at org.jetbrains.dokka.base.DokkaBase$psiToDocumentableTranslator$2$1.invoke(DokkaBase.kt:43)
        at org.jetbrains.dokka.plugability.LazyEvaluated.get$core(LazyEvaluated.kt:8)
        at org.jetbrains.dokka.plugability.DokkaContextConfigurationImpl.actions(DokkaContext.kt:164)
        at org.jetbrains.dokka.plugability.DokkaContextConfigurationImpl.get(DokkaContext.kt:147)
        at org.jetbrains.dokka.base.generation.SingleModuleGeneration.translateSources(SingleModuleGeneration.kt:113)
        at org.jetbrains.dokka.base.generation.SingleModuleGeneration.access$translateSources(SingleModuleGeneration.kt:21)
        at org.jetbrains.dokka.base.generation.SingleModuleGeneration$createDocumentationModels$1$invokeSuspend$$inlined$parallelMap$1$1.invokeSuspend(parallelCollectionOperations.kt:17)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

Coroutines branch (note: Dokka is published locally via `./gradlew publishToMavenLocal` with the corresponding version): https://github.com/Kotlin/kotlinx.coroutines/tree/dokka-update, command: `./gradlew cleanDokkaHtmlMultiModule dokkaHtmlMultiModule --no-daemon --stacktrace`

Dokka is published from your PR, with two changes -- version for publishing and commented out `Dispatchers.shutdown`

**Comment by aSemy** [comment]
I get an error when looking at `AnalysisEnvironment` about missing dependencies... 

image


I am very confused why this might be. I don't think this PR changes the dependencies.

**Comment by qwwdfsad** [comment]
>The error would probably go away if I did a full rebuild, then the shadowed jar would contain the missing dependencies.

Yeah, you have to explicitly reimport your project into IDEA

**Comment by aSemy** [comment]
@qwwdfsad I've also added an option so you can configure the `finalizeCoroutines` option.

Add this config to the bottom of `kotlinx.coroutines/gradle/dokka.gradle.kts`

```kotlin
tasks.withType<AbstractDokkaTask>().configureEach {
    finalizeCoroutines.set(false)
}
```

**Comment by aSemy** [comment]
🎉  
image

**Comment by adam-enko** [comment]
Obsolete. Dokka Plugin v2 will use the worker API. https://github.com/Kotlin/dokka/pull/3695

**Pull request closed without merging**
